[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Update Parchment Glove when hand is played
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.hands_played = G.GAME.hands_played + 1"
position = "after"
payload = 'StrangeLib.dynablind.update_blind_scores(StrangeLib.dynablind.find_blind("bl_pencil_glove"))'
match_indent = true
