[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Make royal deck only give face cards
[[patches]]
[patches.pattern]
target = "back.lua"
pattern = '''
if self.effect.config.remove_faces then
    G.GAME.starting_params.no_faces = true
end
'''
position = "after"
payload = '''
if self.effect.config.pencil_only_faces then
    G.GAME.starting_params.pencil_only_faces = true
end
'''
match_indent = true
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if keep then card_protos[#card_protos+1] = {s=_s,r=_r,e=_e,d=_d,g=_g} end"
position = "before"
payload = "if self.GAME.starting_params.pencil_only_faces and not SMODS.Ranks[v.value].face then keep = false end"
match_indent = false