[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Boosted Booster Deck
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.ability[k] = v"
position = "after"
payload = '''
if self.ability.set == 'Booster' and k == 'choose' and G.GAME.modifiers.booster_choices then
    self.ability['choose'] = self.ability['choose'] + G.GAME.modifiers.booster_choices
end
'''
match_indent = true
# wtf?
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "G.GAME.pack_choices = self.config.center.config.choose or 1"
position = "after"
payload = "G.GAME.pack_choices = self.ability.choose"
match_indent = true
