[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add exponential ante modifier
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling"
position = "at"
payload = "local blind_amt = (get_blind_amount(G.GAME.round_resets.blind_ante)*G.GAME.starting_params.ante_scaling)^(G.GAME.starting_params.ante_scaling_exponential or 1)*(blind_choice.config.get_mult and blind_choice.config:get_mult() or blind_choice.config.mult)"
match_indent = true
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling"
position = "at"
payload = "self.chips = (get_blind_amount(G.GAME.round_resets.ante)*G.GAME.starting_params.ante_scaling)^(G.GAME.starting_params.ante_scaling_exponential or 1)*self.mult"
match_indent = true
